// <auto-generated />
using System;
using MeuProjeto.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeuProjeto.Migrations
{
    [DbContext(typeof(LegendsStoreContext))]
    [Migration("20260706060335_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompraJogo", b =>
                {
                    b.Property<int>("ComprasId")
                        .HasColumnType("int");

                    b.Property<int>("JogosId")
                        .HasColumnType("int");

                    b.HasKey("ComprasId", "JogosId");

                    b.HasIndex("JogosId");

                    b.ToTable("CompraJogo");
                });

            modelBuilder.Entity("JogoUsuario", b =>
                {
                    b.Property<int>("JogosId")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosId")
                        .HasColumnType("int");

                    b.HasKey("JogosId", "UsuariosId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("JogoUsuario");
                });

            modelBuilder.Entity("MeuProjeto.Models.Carrinho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JogoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Carrinhos");
                });

            modelBuilder.Entity("MeuProjeto.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("MeuProjeto.Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("criado_em")
                        .HasColumnType("datetime2");

                    b.Property<float>("valor_total")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("MeuProjeto.Models.CompraJogo", b =>
                {
                    b.Property<int>("compraId")
                        .HasColumnType("int");

                    b.Property<int>("jogoId")
                        .HasColumnType("int");

                    b.HasKey("compraId", "jogoId");

                    b.HasIndex("jogoId");

                    b.ToTable("CompraJogos");
                });

            modelBuilder.Entity("MeuProjeto.Models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("banner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("capa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("categoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("criado_em")
                        .HasColumnType("datetime2");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("valor")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("categoriaId");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("MeuProjeto.Models.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("compraId")
                        .HasColumnType("int");

                    b.Property<DateTime>("criado_em")
                        .HasColumnType("datetime2");

                    b.Property<string>("metodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("compraId")
                        .IsUnique();

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("MeuProjeto.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("criado_em")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pontos")
                        .HasColumnType("int");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MeuProjeto.Models.UsuarioJogo", b =>
                {
                    b.Property<int>("usuarioId")
                        .HasColumnType("int");

                    b.Property<int>("jogoId")
                        .HasColumnType("int");

                    b.HasKey("usuarioId", "jogoId");

                    b.HasIndex("jogoId");

                    b.ToTable("UsuarioJogos");
                });

            modelBuilder.Entity("CompraJogo", b =>
                {
                    b.HasOne("MeuProjeto.Models.Compra", null)
                        .WithMany()
                        .HasForeignKey("ComprasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeuProjeto.Models.Jogo", null)
                        .WithMany()
                        .HasForeignKey("JogosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JogoUsuario", b =>
                {
                    b.HasOne("MeuProjeto.Models.Jogo", null)
                        .WithMany()
                        .HasForeignKey("JogosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeuProjeto.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeuProjeto.Models.Carrinho", b =>
                {
                    b.HasOne("MeuProjeto.Models.Jogo", "Jogo")
                        .WithMany("Carrinhos")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeuProjeto.Models.Usuario", "Usuario")
                        .WithMany("Carrinhos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MeuProjeto.Models.Compra", b =>
                {
                    b.HasOne("MeuProjeto.Models.Usuario", "Usuario")
                        .WithMany("Compras")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MeuProjeto.Models.CompraJogo", b =>
                {
                    b.HasOne("MeuProjeto.Models.Compra", "Compra")
                        .WithMany("CompraJogos")
                        .HasForeignKey("compraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeuProjeto.Models.Jogo", "Jogo")
                        .WithMany("CompraJogos")
                        .HasForeignKey("jogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("MeuProjeto.Models.Jogo", b =>
                {
                    b.HasOne("MeuProjeto.Models.Categoria", "Categoria")
                        .WithMany("Jogos")
                        .HasForeignKey("categoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("MeuProjeto.Models.Pagamento", b =>
                {
                    b.HasOne("MeuProjeto.Models.Compra", "Compra")
                        .WithOne("Pagamento")
                        .HasForeignKey("MeuProjeto.Models.Pagamento", "compraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");
                });

            modelBuilder.Entity("MeuProjeto.Models.UsuarioJogo", b =>
                {
                    b.HasOne("MeuProjeto.Models.Jogo", "Jogo")
                        .WithMany("UsuarioJogos")
                        .HasForeignKey("jogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeuProjeto.Models.Usuario", "Usuario")
                        .WithMany("UsuarioJogos")
                        .HasForeignKey("usuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MeuProjeto.Models.Categoria", b =>
                {
                    b.Navigation("Jogos");
                });

            modelBuilder.Entity("MeuProjeto.Models.Compra", b =>
                {
                    b.Navigation("CompraJogos");

                    b.Navigation("Pagamento")
                        .IsRequired();
                });

            modelBuilder.Entity("MeuProjeto.Models.Jogo", b =>
                {
                    b.Navigation("Carrinhos");

                    b.Navigation("CompraJogos");

                    b.Navigation("UsuarioJogos");
                });

            modelBuilder.Entity("MeuProjeto.Models.Usuario", b =>
                {
                    b.Navigation("Carrinhos");

                    b.Navigation("Compras");

                    b.Navigation("UsuarioJogos");
                });
#pragma warning restore 612, 618
        }
    }
}
